env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  import/extensions: 0,
  no-console: 0,
  no-param-reassign: [2, { "props": false }],
  react/function-component-definition: [2, { "namedComponents": ["function-declaration", "arrow-function"] }],
  react/prop-types: 0,
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
}
